[auth]
redirect_uri = "https://writingtutorstreamlit.app"
cookie_secret = "writingtutorisdabest"
client_id = "479597936494-2gmqefg0u1i18c9vb6fc008raj8pufud.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
